@startuml Login
actor Utilizador
boundary Interface
control GestorConta
entity Persistencia

Utilizador -> Interface: Introduz email e senha
Interface -> GestorConta: Solicita autenticação
GestorConta -> Persistencia: Verifica utilizador(email, senha)
Persistencia --> GestorConta: Resultado (válido/inválido)
GestorConta --> Interface: Resposta de autenticação
Interface --> Utilizador: Mostra mensagem (Login OK / Falhou)
@enduml
