@startuml
actor Utilizador
Utilizador -> InterfaceRegisto : Pedir registo
InterfaceRegisto -> Conta : Criar nova conta
Conta -> GuardarDados : Guardar conta
GuardarDados --> Conta : Conta guardada
Conta --> InterfaceRegisto : Sucesso
InterfaceRegisto --> Utilizador : Conta registada
@enduml
