@startuml
title Diagrama de Sequência – Gerir Despesa

actor "Utilizador" as U
participant "Sistema" as S

U -> S: Inserir descrição, valor, data e categoria
S -> S: Validar dados
S --> U: Despesa guardada com sucesso

@enduml
