@startuml
title Sequência Gestao de Finanças Pessoais
actor "Utilizador" as U
participant "Sistema" as S
U -> S: Registar Conta
S --> U: Conta registada com sucesso
U -> S: Login
S --> U: Autenticação bem-sucedida
U -> S: Gerir Perfil
S --> U: Perfil atualizado
U -> S: Gerir Transações
S --> U: Transação adicionada/atualizada/removida~
U -> S: Gerir Categorias
S --> U: Categoria adicionada/atualizada/removida
U -> S: Consultar Relatórios
S --> U: Relatórios exibidos
U -> S: Guardar Dados (Persistência)
S --> U: Dados guardados com sucesso




@enduml
