@startuml
title Diagrama de Sequência – Consultar Relatórios

actor "Utilizador" as U
participant "Sistema" as S

U -> S: Selecionar período ou categoria
S -> S: Gerar relatório
S --> U: Mostrar relatório

@enduml
