@startuml
title Diagrama de Sequência – Gestão de Transação

actor "Utilizador" as User
participant "ui:UITransacao" as UITransacao
participant "t:Transacao" as Transacao
participant "c:Categoria" as Categoria
participant "u:Utilizador" as Utilizador
participant "p:Persistencia" as Persistencia

== Abrir Interface Transação ==
User -> UITransacao: UITransacao()
UITransacao -> Transacao: Transacao()
Transacao -> Categoria: Categoria()
UITransacao -> Utilizador: Utilizador()
UITransacao -> Persistencia: Persistencia()

== Preencher Transação ==
User -> UITransacao: Set_Descricao(Descricao)
UITransacao -> Transacao: set_Descricao(Descricao)

User -> UITransacao: Set_Valor(Valor)
UITransacao -> Transacao: set_Valor(Valor)

User -> UITransacao: Set_Data(Data)
UITransacao -> Transacao: set_Data(Data)

User -> UITransacao: Set_Categoria(NomeCategoria)
UITransacao -> Transacao: set_Categoria(NomeCategoria)

Transacao -> Categoria: Set_Nome(NomeCategoria)
Categoria -> Categoria: validar()

== Guardar Transação ==
User -> UITransacao: Guardar()
UITransacao -> Persistencia: GuardarTransacao(t)
Persistencia --> UITransacao: Confirmação "Transação guardada"

== Consultar Transações ==
User -> UITransacao: Consultar()
UITransacao -> Persistencia: ObterTransacoes(u)
Persistencia --> UITransacao: Lista de Transações
UITransacao --> User: Mostra Transações

== Remover Transação ==
User -> UITransacao: Remover(id)
UITransacao -> Persistencia: EliminarTransacao(id)
Persistencia --> UITransacao: Confirmação "Transação removida"
UITransacao --> User: Mensagem de sucesso
@enduml
