@startuml Classes
class Utilizador {
    -id : int
    -nome : string
    -email : string
    -password : string
    -perfil : string
    +registar()
    +login()
    +gerirPerfil()
     +getters() :void
     +setters() :void 
}

