@startuml
title Diagrama de Classes - Gestão de Finanças Pessoais

' ==== CLASSES ====
class Utilizador {
  - id : int
  - nome : string
  - email : string
  - password : string
  - perfil : string
  --
  + registar() : void
  + login() : bool
  + editarPerfil() : void
}

class Administrador {
  + gerirUtilizadores() : void
}

class Transacao {
  - id : int
  - descricao : string
  - valor : float
  - data : date
  - categoria : string
  - tipo : string ' receita ou despesa
  --
  + validarValor() : bool
  + guardarTransacao() : void
}

class Categoria {
  - nome : string
  --
  + criarCategoria() : void
  + listarCategorias() : List<string>
}


class Persistencia {
  --
  + guardarDados() : void
  + carregarDados() : List<Transacao>
}

' ==== RELAÇÕES ENTRE CLASSES ====
Administrador --|> Utilizador
Utilizador "1" --> "*" Transacao : cria
Transacao "*" --> "1" Categoria : pertence
Relatorio --> Transacao : usa
Utilizador --> Persistencia : grava/carrega
Transacao --> Persistencia : grava/carrega
@enduml
