@startuml
title Diagrama Geral - Gestão de Finanças Pessoais

!include CasosDeUso/caso_registar_utilizador.plantuml
!include CasosDeUso/caso_adicionar_receita.plantuml
!include CasosDeUso/caso_listar_receitas.plantuml

' --- Inclui todas as classes ---
!include Classes/classe_utilizador.plantuml
!include Classes/classe_uireceita.plantuml
!include Classes/classe_receita.plantuml
!include Classes/classe_categoria.plantuml
!include Classes/classe_persistencia.plantuml

' --- Inclui as sequências ---
!include Sequencias/sequencia.plantuml

@enduml
